export const ROUTER_URL = {
    AUTH: {
        LOGIN: "/dang-nhap",
        SIGN_UP: "/dang-ky",
        FORGOT_PASSWORD: "/quen-mat-khau",
        RESET_PASSWORD: "/doi-mat-khau",
        VERIFY_EMAIL: "/api/auth/verify-email",
        UNAUTHOZIZED: "/auth/unauthorized",
    },
    COMMON: {
        HOME: "/",
        ABOUT: "/about",
        CONTACT: "/contact",
        FAQ: "/faq",
        PAYMENT_CALLBACK: "/payments/payos-callback",
        PAYMENT_CALLBACK_API: "/api/Payments/payos-callback",
    },
    CLIENT: {
        BUY_MOTOR: "/mua-xe",
        SELL_MOTOR: "/ban-xe",
        ACCESSORIES: "/phu-kien",
        FAVORITE: "/yeu-thich",
        NEWS: "/tin-tuc",
        NEWS_DETAIL: "/tin-tuc/:id",
        NEWS_CATEGORY: "/tin-tuc/category/:categoryId",
        PRODUCT_LIST_BY_CATEGORY_ID: "/san-pham",
        PRODUCT_DETAIL: "/san-pham/:id",
        CART: "/gio-hang",
        ORDER: "/tao-don-hang",
        PAYMENT: "/tao-thanh-toan",
        ORDER_HISTORY: "/lich-su-don-hang",
        ORDER_DETAIL: "/don-hang/:id",
    },
    // BUYER ROUTES
    BUYER: {
        BASE: "/buyer",
        DASHBOARD: "/buyer/trang-chu",
        PROFILE: "/buyer/ho-so",
        ORDERS: "/buyer/don-hang",
        ORDER_HISTORY: "/buyer/lich-su-don-hang",
        ORDER_DETAIL: "/buyer/don-hang/:id",
        FAVORITES: "/buyer/yeu-thich",
        CART: "/buyer/gio-hang",
        NOTIFICATIONS: "/buyer/thong-bao",
        WALLET: "/buyer/vi-tien",
        SETTINGS: "/buyer/cai-dat",
        SUPPORT: "/buyer/ho-tro",
    },
    // SELLER ROUTES
    SELLER: {
        BASE: "/seller",
        DASHBOARD: "/seller",
        PROFILE: "/seller/ho-so",
        SHOP: "/seller/cua-hang",
        PRODUCTS: "/seller/san-pham",
        ADD_PRODUCT: "/seller/them-san-pham",
        EDIT_PRODUCT: "/seller/sua-san-pham",
        ORDERS: "/seller/don-hang",
        ORDER_MANAGEMENT: "/seller/quan-ly-don-hang",
        INVENTORY: "/seller/kho-hang",
        ANALYTICS: "/seller/thong-ke",
        REVIEWS: "/seller/danh-gia",
        PROMOTIONS: "/seller/khuyen-mai",
        NOTIFICATIONS: "/seller/thong-bao",
        WALLET: "/seller/vi-tien",
        SETTINGS: "/seller/cai-dat",
        SUPPORT: "/seller/ho-tro",
    },
    // SHIPPER ROUTES
    SHIPPER: {
        BASE: "/shipper",
        DASHBOARD: "/shipper/trang-chu",
        PROFILE: "/shipper/ho-so",
        DELIVERY_ORDERS: "/shipper/don-giao-hang",
        ACTIVE_DELIVERIES: "/shipper/dang-giao",
        DELIVERY_HISTORY: "/shipper/lich-su-giao-hang",
        ROUTE_PLANNING: "/shipper/lap-tuyen-duong",
        EARNINGS: "/shipper/thu-nhap",
        PERFORMANCE: "/shipper/hieu-suat",
        NOTIFICATIONS: "/shipper/thong-bao",
        WALLET: "/shipper/vi-tien",
        SETTINGS: "/shipper/cai-dat",
        SUPPORT: "/shipper/ho-tro",
    },
    ADMIN: {
        BASE: "/admin",
        OVERVIEW: "/admin/tong-quan",
        USERS: "/admin/quan-ly-nguoi-dung",
        CATEGORIES: "/admin/quan-ly-danh-muc",
        PRODUCTS: "/admin/quan-ly-san-pham",
        ACCESSORIES: "/admin/quan-ly-phu-kien",
        NEWS: "/admin/quan-ly-tin-tuc",
        ORDERS: "/admin/quan-ly-don-hang",
        REPORTS: "/admin/bao-cao",
        REVIEWS: "/admin/quan-ly-danh-gia",
        STATISTICS: "/admin/thong-ke",
        SETTINGS: "/admin/cai-dat",
        UPDATE_USER_PROFILE: "update-user-profile",
    }
};